### ISSUE TITLE
Probleme EW11 und IOBroker 

### ISSUE THREAD

**Issue by Sefina-DS** [ioBroker/modbus-templates#22]
Hi zusammen,

ich habe einen Deye SUN 12 K und an diesen ist ein EW11 (Elfin) angebunden.
Dieser ist als Server eingestellt.

Die Register habe ich eingerichtet.

Ich bekomme die Daten aus dem Inverter, sodass die Kommunikation funktioniert.

Ich bekomme mehrmals in der Minute Verbindungsabbrüche, sodass das gesamte Log damit voll ist.

Hat, wer 'ne Idee, was ich noch ändern kann?
![ew11 tcp](https://github.com/ioBroker/modbus-templates/assets/35521885/17f99173-6e20-4cde-8eb5-573787103362)
![ew11 serial](https://github.com/ioBroker/modbus-templates/assets/35521885/344748ec-088d-48f0-a884-2265357a144b)
![iobroker-adapter](https://github.com/ioBroker/modbus-templates/assets/35521885/b57304ba-a6f2-4531-8f76-6ab413a7e400)
![iobroker-register](https://github.com/ioBroker/modbus-templates/assets/35521885/65b797fc-9c4f-4911-881b-bda28dce1a88)
![iobroker-objekte](https://github.com/ioBroker/modbus-templates/assets/35521885/215a4bad-cc4a-45d9-8616-abd6a0c4dc79)

**Comment by Apollon77** [comment]
This repo is not for support. Please file an issue with modbus adapter or post in forum
